export interface WordBook {
  id: number;
  attributes: {
    coverImage: string;
    title: string;
    description: string;
    createdAt: string;
  };
}

// export const wordbooks: WordBook[] = [
//   {
//     id: 1,
//     title: '테스트 단어장 1',
//     description: '우선순위 영단어 22장',
//     createdAt: '2021-12-04',
//     coverImage:
//       'https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1635259843/tlog/cover/Screen_Shot_2021-10-24_at_6.31.23_PM_deno9r.png?w=1080&q=75',
//     contents: [
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//     ],
//   },
//   {
//     id: 2,
//     title: '테스트 단어장 2',
//     description: '우선순위 영단어 23장',
//     createdAt: '2021-12-04',
//     coverImage:
//       'https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1635259843/tlog/cover/Screen_Shot_2021-10-24_at_6.31.23_PM_deno9r.png?w=1080&q=75',
//     contents: [
//       {
//         word: 'run',
//         description: '달려라 달려라 달려라 왕바우 너도 한번 달려보자',
//       },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//       { word: 'run', description: '달리다' },
//     ],
//   },
// ];
