import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import WordBookGallery from '../components/WordBookGallery';
import Layout from '../components/Layout';
import { useSWR } from '../apis';

const Home: NextPage = () => {
  const { data } = useSWR<any>('/api/words-notes');
  const wordBooks = React.useMemo(() => {
    return data?.data ?? [];
  }, [data]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <WordBookGallery wordBooks={wordBooks} />
      </Layout>
    </div>
  );
};

export default Home;
